apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets

resources:
  - namespace.yaml

helmCharts:
  - repo: https://charts.external-secrets.io
    name: external-secrets
    releaseName: external-secrets
    namespace: external-secrets
    version: 0.9.16
    valuesFile: values.yaml
