# https://taskfile.dev

version: "3"

includes:
  k8s: tasks/k8s
  utils:
    taskfile: tasks/utils
    internal: true

interval: 20ms

dotenv: [".env"]

tasks:
  default: task --list

  vet: go vet ./...
  fmt: go fmt ./...

  bootstrap:
    cmds:
      - task: utils:bootstrap

  test:
    sources:
      - "**/*.go"
    cmds:
      - go test ./...

  build:
    sources:
      - "**/*.go"
    generates:
      - ./bin/echo-server
    env:
      CGO_ENABLED: "0"
    cmds:
      - go build -o ./bin/echo-server ./cmd/echo-server/

  start:
    deps:
      - task: build
    cmds:
      - ./bin/echo-server

  call:
    silent: true
    vars:
      ENDPOINT: '{{.ENDPOINT | default "localhost:8080"}}'
      MESSAGE: '{{.MESSAGE | default "🙈🙉🙊"}}'
      JSON_MESSAGE: '{ "message": {{ .MESSAGE | quote }} }'
    cmds:
      - curl -i http://{{.ENDPOINT}}/echo -d {{.JSON_MESSAGE | quote}}

  sync:
    silent: true
    deps:
      - task: build
      - task: k8s:create-cluster
    vars:
      BINARY_CHECKSUM:
        sh: "sha1sum ./bin/echo-server | cut -d ' ' -f 1"

      IMAGE_NAME: "localhost:5000/echo-server"
      IMAGE_TAG: '{{.IMAGE_NAME}}:{{.BINARY_CHECKSUM | default "latest"}}'

    sources:
      - "./bin/echo-server"
      - "Dockerfile"

    cmds:
      # build and push the container image
      - gum spin --show-error --title="Building image {{.IMAGE_TAG}} ..." -- docker build --tag {{.IMAGE_TAG}} ./
      - task: utils:log
        vars: { MESSAGE: "Container image {{.IMAGE_TAG}} built" }

      - gum spin --show-error --title="Pushing image {{.IMAGE_TAG}} ..." -- docker push {{.IMAGE_TAG}}
      - task: utils:log
        vars: { MESSAGE: "Container image {{.IMAGE_TAG}} pushed" }

      # make sure all the resources have been created and update the image tag in the cluster
      - task: k8s:apply
        vars: { MANIFESTS: "kubernetes/echo-server" }
      - kubectl -n echo-server set image deployment/echo-server echo-server=registry.{{.IMAGE_TAG}}

  clean:
    silent: true
    ignore_error: true
    vars:
      ITEMS_TO_CLEAN: ["./bin", "./tmp", "./.task"]
    prompt: "Delete the following items? {{.ITEMS_TO_CLEAN}}"
    cmds:
      - for: { var: ITEMS_TO_CLEAN }
        cmd: rm -rv {{.ITEM}}

  down:
    cmds:
      - task: k8s:delete-cluster
      - task: clean
